// Minimal mock unit and terrain data for tests.
// Covers all unit types referenced in test files.

import type { UnitData, TerrainData } from "../game/types";

export const MOCK_UNITS: Record<string, UnitData> = {
  infantry: {
    id: "infantry",
    name: "Infantry",
    domain: "ground",
    move_type: "foot",
    move_points: 3,
    vision: 2,
    cost: 1000,
    can_capture: true,
    tags: ["infantry_class"],
    weapons: [
      {
        id: "machine_gun",
        name: "Machine Gun",
        min_range: 1,
        max_range: 1,
        can_counterattack: true,
        ammo: -1,
        damage_table: {
          infantry: 55,
          mech: 45,
          recon: 12,
          tank: 5,
          md_tank: 1,
          artillery: 15,
          t_copter: 30,
          b_copter: 7,
        },
      },
    ],
    special_actions: [],
  },
  mech: {
    id: "mech",
    name: "Mech",
    domain: "ground",
    move_type: "mech",
    move_points: 2,
    vision: 2,
    cost: 3000,
    can_capture: true,
    tags: ["infantry_class"],
    weapons: [
      {
        id: "bazooka",
        name: "Bazooka",
        min_range: 1,
        max_range: 1,
        can_counterattack: true,
        ammo: 3,
        damage_table: { infantry: 0, tank: 55, md_tank: 25, artillery: 70 },
      },
      {
        id: "machine_gun",
        name: "Machine Gun",
        min_range: 1,
        max_range: 1,
        can_counterattack: true,
        ammo: -1,
        damage_table: { infantry: 65, mech: 55, tank: 6, t_copter: 35 },
      },
    ],
    special_actions: [],
  },
  tank: {
    id: "tank",
    name: "Tank",
    domain: "ground",
    move_type: "tread",
    move_points: 6,
    vision: 3,
    cost: 7000,
    can_capture: false,
    tags: ["heavy_vehicle"],
    weapons: [
      {
        id: "cannon",
        name: "Cannon",
        min_range: 1,
        max_range: 1,
        can_counterattack: true,
        ammo: 9,
        damage_table: { infantry: 0, mech: 0, tank: 55, md_tank: 15, artillery: 70, recon: 85 },
      },
      {
        id: "machine_gun",
        name: "Machine Gun",
        min_range: 1,
        max_range: 1,
        can_counterattack: true,
        ammo: -1,
        damage_table: { infantry: 75, mech: 70, tank: 6, t_copter: 40 },
      },
    ],
    special_actions: [],
  },
  artillery: {
    id: "artillery",
    name: "Artillery",
    domain: "ground",
    move_type: "tread",
    move_points: 5,
    vision: 1,
    cost: 6000,
    can_capture: false,
    tags: ["indirect"],
    weapons: [
      {
        id: "cannon",
        name: "Cannon",
        min_range: 2,
        max_range: 3,
        can_counterattack: false,
        ammo: 9,
        damage_table: { infantry: 90, mech: 85, tank: 70, artillery: 75 },
      },
    ],
    special_actions: [],
  },
  apc: {
    id: "apc",
    name: "APC",
    domain: "ground",
    move_type: "tread",
    move_points: 6,
    vision: 1,
    cost: 5000,
    fuel: 70,
    fuel_per_turn: 1,
    can_capture: false,
    tags: ["light_vehicle", "transport"],
    weapons: [],
    transport: { capacity: 1, allowed_tags: ["infantry_class"] },
    special_actions: ["resupply"],
  },
  recon: {
    id: "recon",
    name: "Recon",
    domain: "ground",
    move_type: "tires",
    move_points: 8,
    vision: 5,
    cost: 4000,
    can_capture: false,
    tags: ["light_vehicle"],
    weapons: [
      {
        id: "machine_gun",
        name: "Machine Gun",
        min_range: 1,
        max_range: 1,
        can_counterattack: true,
        ammo: -1,
        damage_table: { infantry: 70, mech: 65, tank: 6 },
      },
    ],
    special_actions: [],
  },
  t_copter: {
    id: "t_copter",
    name: "Chinook",
    domain: "air",
    move_type: "air",
    move_points: 6,
    vision: 2,
    cost: 5000,
    fuel: 99,
    fuel_per_turn: 2,
    can_capture: false,
    tags: ["helicopter", "transport"],
    weapons: [],
    transport: { capacity: 1, allowed_tags: ["infantry_class"] },
    special_actions: [],
  },
  b_copter: {
    id: "b_copter",
    name: "Apache",
    domain: "air",
    move_type: "air",
    move_points: 6,
    vision: 3,
    cost: 9000,
    fuel: 99,
    fuel_per_turn: 2,
    can_capture: false,
    tags: ["helicopter"],
    weapons: [
      {
        id: "missiles",
        name: "Missiles",
        min_range: 1,
        max_range: 1,
        can_counterattack: true,
        ammo: 6,
        damage_table: { tank: 55, artillery: 65, infantry: 0 },
      },
      {
        id: "machine_gun",
        name: "Machine Gun",
        min_range: 1,
        max_range: 1,
        can_counterattack: true,
        ammo: -1,
        damage_table: { infantry: 75, mech: 75, tank: 6, t_copter: 65 },
      },
    ],
    special_actions: [],
  },
  fighter: {
    id: "fighter",
    name: "Fighter",
    domain: "air",
    move_type: "air",
    move_points: 9,
    vision: 2,
    cost: 20000,
    fuel: 99,
    fuel_per_turn: 5,
    can_capture: false,
    tags: ["plane"],
    weapons: [
      {
        id: "missiles",
        name: "Missiles",
        min_range: 1,
        max_range: 1,
        can_counterattack: true,
        ammo: 9,
        damage_table: { t_copter: 100, b_copter: 100, fighter: 55, bomber: 100 },
      },
    ],
    special_actions: [],
  },
  submarine: {
    id: "submarine",
    name: "Sub",
    domain: "sea",
    move_type: "ship",
    move_points: 5,
    vision: 5,
    cost: 20000,
    fuel: 60,
    fuel_per_turn: 1,
    can_capture: false,
    tags: ["ship"],
    weapons: [
      {
        id: "torpedoes",
        name: "Torpedoes",
        min_range: 1,
        max_range: 1,
        can_counterattack: true,
        ammo: 6,
        damage_table: { submarine: 55, lander: 95, cruiser: 25 },
      },
    ],
    special_actions: ["submerge", "surface"],
  },
  lander: {
    id: "lander",
    name: "Lander",
    domain: "sea",
    move_type: "trans",
    move_points: 6,
    vision: 1,
    cost: 12000,
    fuel: 99,
    fuel_per_turn: 1,
    can_capture: false,
    tags: ["ship", "transport"],
    weapons: [],
    transport: { capacity: 2, allowed_tags: ["infantry_class", "light_vehicle", "heavy_vehicle"] },
    special_actions: [],
  },
};

export const MOCK_TERRAIN: Record<string, TerrainData> = {
  plains: {
    id: "plains",
    name: "Plains",
    defense_stars: 0,
    is_property: false,
    can_capture: false,
    income: 0,
    can_produce: [],
    can_build_trench: true,
    can_build_fob: true,
    movement_costs: { foot: 1, mech: 1, tires: 2, tread: 1, air: 1, ship: -1, trans: -1 },
  },
  city: {
    id: "city",
    name: "City",
    defense_stars: 3,
    is_property: true,
    can_capture: true,
    income: 1000,
    can_produce: [],
    can_build_trench: false,
    can_build_fob: false,
    movement_costs: { foot: 1, mech: 1, tires: 1, tread: 1, air: 1, ship: -1, trans: -1 },
  },
  factory: {
    id: "factory",
    name: "Factory",
    defense_stars: 3,
    is_property: true,
    can_capture: true,
    income: 1000,
    can_produce: ["infantry", "tank", "apc", "artillery"],
    can_build_trench: false,
    can_build_fob: false,
    movement_costs: { foot: 1, mech: 1, tires: 1, tread: 1, air: 1, ship: -1, trans: -1 },
  },
  hq: {
    id: "hq",
    name: "HQ",
    defense_stars: 4,
    is_property: true,
    can_capture: true,
    income: 1000,
    can_produce: [],
    can_build_trench: false,
    can_build_fob: false,
    movement_costs: { foot: 1, mech: 1, tires: 1, tread: 1, air: 1, ship: -1, trans: -1 },
  },
  mountain: {
    id: "mountain",
    name: "Mountain",
    defense_stars: 4,
    is_property: false,
    can_capture: false,
    income: 0,
    can_produce: [],
    can_build_trench: false,
    can_build_fob: false,
    movement_costs: { foot: 2, mech: 1, tires: -1, tread: -1, air: 1, ship: -1, trans: -1 },
  },
  sea: {
    id: "sea",
    name: "Sea",
    defense_stars: 0,
    is_property: false,
    can_capture: false,
    income: 0,
    can_produce: [],
    can_build_trench: false,
    can_build_fob: false,
    movement_costs: { foot: -1, mech: -1, tires: -1, tread: -1, air: 1, ship: 1, trans: 1 },
  },
  temporary_fob: {
    id: "temporary_fob",
    name: "FOB",
    defense_stars: 3,
    is_property: false,
    can_capture: false,
    income: 0,
    can_produce: [],
    can_build_trench: false,
    can_build_fob: false,
    movement_costs: { foot: 1, mech: 1, tires: 1, tread: 1, air: 1, ship: -1, trans: -1 },
  },
};
